image: ubuntu

definitions:
  steps:
    - step: &install
        name: 'Install Dependencies'
        image: node:16
        script:
          - npm install

pipelines:
  default:
    - step: *install

  branches:
    develop:
      - step: *install
    master:
      - step: *install
